### PR TITLE
Fix issues with boxed types

### LINKED ISSUE #1403: Operators not allowed on boxed types
If I use boxed types like `roInt` or `roLongInteger`, the compiler throws errors.

```brighterscript
function math(a as rolonginteger, b as longinteger)
    c = a + b
    c = a - b
    c = a * b
    c = a / b
    c = a \ b

    d = a mod b
    d = a ^ b

    a++
    a--
    a += 1
    a -= 1
    a *= 1
    a /= 1
    a \= 1
    a <<= 1
    a >>= 1

    ? 1 << (2 as roInt)
    ? (1 as roInt) << 2
    ? a and b
    ? a or b

    j = a = b
    j = a <> b
    j = a < b
    j = a <= b
    j = a > b
    j = a >= b
end function
```

Image

### PR DESCRIPTION
**Pull request by markwpearce**
Fixes #1403

Basically, any place where a simple `integer` or `float` could be, the equivalent boxed type is allowed. BrightScript does automatic type conversion between boxed and un-boxed types, so we should treat them the same.

### CODE REVIEW

File: src/astUtils/reflection.ts [hunk 1]
```diff
@@ -309,32 +309,39 @@ export function isPrintSeparatorExpression(element: any): element is PrintSepara
 }
 
 // BscType reflection
-export function isStringType(value: any): value is StringType {
-    return value?.kind === BscTypeKind.StringType;
+export function isStringType(value: any, includeBoxed = true): value is StringType {
```
Comment (TwitchBronBron) [inline src/astUtils/reflection.ts:312]: Shouldn't these be `false` by default, except in the locations where you know it's allowed? Also, i don't see anywhere that you're passing `false`, so the entire codebase will now be supporting boxed by default. Is all of that okay? Feels a little aggressive, but I don't have all the context.

Comment (markwpearce) [reply src/astUtils/reflection.ts:312]: yeah.. I was thinking this too (`includeBoxed = false` by default)... But everywhere in the code where I check a primitive type, I was going to have to  add `true` anyway

The places I check for these primitive types are in typeCompatibility checks,  operator checks, etc... and as far as I know, BrightScript basically treats these the same anyway.

Can you think of a time a Boxed type is not allowed, when a non-boxed type would be?

Comment (TwitchBronBron) [reply src/astUtils/reflection.ts:312]: You're right. it's probably fine. I'm imagining some future box/not-boxed validations, but you still have the boolean, and in 99.9% of the time, nobody will care. 

So this is fine as-is

Comment (TwitchBronBron) [reply src/astUtils/reflection.ts:312]: Actually, I still have a few thoughts on this.

I think what I'd really like to see is something like:
```
function isStringType()
function isRoStringType()
function isStringTypeLike()
```

I know that's a lot more work to add these to all the boxables, but in the future I envision adding some extra opt-in diagnostics to flag boxed/non-boxed interactions in some cases, and overloading this `isStringType` feels just a little "incorrect" since we _are_ actually comparing two separate types. 

Thoughts?

Comment (markwpearce) [reply src/astUtils/reflection.ts:312]: awesome.. this is better :) 

I'll make the change

**Review by TwitchBronBron — APPROVED** [review]
