### PR TITLE
Prevent circular import crash

### LINKED ISSUE #377: Namespaces that import each other can cause a circular dependency issue
```
RangeError: Maximum call stack size exceeded
    at Program.getFileByPathAbsolute (/Users/chris/.vscode/extensions/rokucommunity.brightscript-2.17.9/node_modules/brighterscript/dist/Program.js:321:26)
    at BrsFile.resolveTypedef (/Users/chris/.vscode/extensions/rokucommunity.brightscript-2.17.9/node_modules/brighterscript/dist/files/BrsFile.js:116:41)
    at EventEmitter.<anonymous> (/Users/chris/.vscode/extensions/rokucommunity.brightscript-2.17.9/node_modules/brighterscript/dist/files/BrsFile.js:129:18)
    at EventEmitter.emit (/Users/chris/.vscode/extensions/rokucommunity.brightscript-2.17.9/node_modules/eventemitter3/index.js:202:33)
    at DependencyGraph.emit (/Users/chris/.vscode/extensions/rokucommunity.brightscript-2.17.9/node_modules/brighterscript/dist/DependencyGraph.js:79:30)
    at EventEmitter.<anonymous> (/Users/chris/.vscode/extensions/rokucommunity.brightscript-2.17.9/node_modules/brighterscript/dist/DependencyGraph.js:114:28)
    at EventEmitter.emit (/Users/chris/.vscode/extensions/rokucommunity.brightscript-2.17.9/node_modules/eventemitter3/index.js:202:33)
    at DependencyGraph.emit (/Users/chris/.vscode/extensions/rokucommunity.brightscript-2.17.9/node_modules/brighterscript/dist/DependencyGraph.js:79:30)
    at EventEmitter.<anonymous> (/Users/chris/.vscode/extensions/rokucommunity.brightscript-2.17.9/node_modules/brighterscript/dist/DependencyGraph.js:114:28)
    at EventEmitter.emit (/Users/chris/.vscode/extensions/rokucommunity.brightscript-2.17.9/node_modules/eventemitter3/index.js:202:33)
[11:02:55:1670 AM]  Validating project
[11:02:55:1670 AM]  Validating project finished. (0.37ms)
```

Example: you have a namespace called `Types`  and a namespace called `Getter`
`Getter` uses `Types` to validate object types. So for example `Getter.Boolean(object, "path.in.object")` will use `Types.isBoolean(value)` under the hood and `Types` internally might use `Getter.<type>()` under the hood for safe object traversal. As a result they import each other leading to the above crash.

### PR DESCRIPTION
**Pull request by TwitchBronBron**
Resolves an issue where circular imports will cause an infinite notification loop in `DependencyGraph`. 
Fixes #377

### CODE REVIEW

File: src/files/XmlFile.ts [hunk 1]
```diff
@@ -489,7 +489,7 @@ export class XmlFile {
 
         if (this.needsTranspiled || extraImportScripts.length > 0) {
             //temporarily add the missing imports as script tags
-            const originalScripts = this.ast.component.scripts;
+            const originalScripts = this.ast.component?.scripts ?? [];
```
Comment (TwitchBronBron) [inline src/files/XmlFile.ts:492]: Unrelated to this PR. Just a little extra safeguarding around potentially-broken component AST.

**Review by chrisdp — APPROVED** [review]
